LIVE_DIM_MAPPING = {
    "stat_time_day": "统计日期",
    "anchor_id": "主播ID",
    "roi2_material_anchor_name": "主播名称",
}

LIVE_IND_MAPPING = {
    "live_show_count_exclude_video_for_roi2": "整体展示次数",
    "live_watch_count_exclude_video_for_roi2": "整体点击次数",
    "live_cvr_rate_exclude_video_for_roi2": "整体点击率(%)",
    "live_convert_rate_exclude_video_for_roi2": "整体转化率(%)",
    "total_pay_order_count_for_roi2_fork": "整体成交订单数",
    "total_prepay_order_count_for_roi2_fork": "整体预售订单数",
    "total_pay_order_gmv_include_coupon_for_roi2_fork": "整体成交金额(含优惠券/补贴)",
    "total_pay_order_gmv_for_roi2_fork": "用户实际支付金额",
    "total_prepay_order_gmv_for_roi2_fork": "整体预售订单金额",
    "total_unfinished_estimate_order_gmv_for_roi2_fork": "整体未完结预售订单预估金额",
    "stat_cost_for_roi2_fork": "整体消耗(元)",
    "basic_stat_cost_for_roi2_v2_fork": "基础消耗(元)",
    "live_exclude_video_ecpm_for_roi2": "整体千次展现费用(元)",
    "live_exclude_video_cpc_for_roi2": "整体点击单价(元)",
    "total_cost_per_pay_order_for_roi2_fork": "整体成交订单成本(元)",
    "total_prepay_and_pay_order_roi2_fork": "整体支付ROI",
    "total_pay_order_coupon_amount_for_roi2_fork": "整体成交智能优惠券金额",
    "total_ecom_platform_subsidy_amount_for_roi2_fork": "电商平台补贴金额",
    "total_prepay_and_pay_settle_roi2_1h": "1小时净成交ROI",
    "total_cost_per_pay_order_settle_for_overall_roi2_1h": "综合净成交订单成本(1小时)",
    "total_prepay_and_pay_settle_overall_roi2_1h": "综合净成交ROI(1小时)",
    "total_order_settle_amount_for_roi2_1h": "1小时净成交金额",
    "total_order_settle_count_for_roi2_1h": "1小时净成交订单数",
    "total_cost_per_pay_order_settle_for_roi2_1h": "1小时净成交订单成本(元)",
    "total_order_real_settle_amount_for_roi2_1h": "用户实际支付净成交金额(1小时)",
    "no_refund_ecom_coupon_amount_for_roi2": "智能优惠券未退款金额",
    "no_refund_ecom_platform_subsidy_amount_for_roi2": "电商平台补贴未退款金额",
    "total_order_settle_amount_rate_for_roi2_1h": "1小时净成交金额结算率(%)",
    "total_order_settle_count_rate_for_roi2_1h": "1小时净成交订单结算率(%)",
    "total_refund_order_count_for_roi2_1h": "1小时内退款订单数",
    "total_refund_order_gmv_for_roi2_1h_all": "1小时内退款金额",
    "total_refund_order_gmv_for_roi2_1h_rate": "1小时内退款率(%)",
    "total_prepay_and_pay_settle_roi2_7d": "7日结算ROI",
    "total_order_settle_amount_for_roi2_7d": "7日结算金额",
    "total_order_settle_count_for_roi2_7d": "7日结算订单数",
    "total_cost_per_pay_order_settle_for_roi2_7d": "7日结算订单成本(元)",
    "total_order_settle_amount_rate_for_roi2_7d": "7日GMV结算率(%)",
    "total_order_settle_count_rate_for_roi2_7d": "7日订单结算率(%)",
    "total_prepay_and_pay_settle_roi2_14d": "14日结算ROI",
    "total_order_settle_amount_for_roi2_14d": "14日结算金额",
    "total_order_settle_count_for_roi2_14d": "14日结算订单数",
    "total_cost_per_pay_order_settle_for_roi2_14d": "14日结算订单成本(元)",
    "total_order_settle_amount_rate_for_roi2_14d": "14日GMV结算率(%)",
    "total_order_settle_count_rate_for_roi2_14d": "14日订单结算率(%)",
    "total_prepay_and_pay_settle_roi2_30d": "30日结算ROI",
    "total_order_settle_amount_for_roi2_30d": "30日结算金额",
    "total_order_settle_count_for_roi2_30d": "30日结算订单数",
    "total_cost_per_pay_order_settle_for_roi2_30d": "30日结算订单成本(元)",
    "total_order_settle_amount_rate_for_roi2_30d": "30日GMV结算率(%)",
    "total_order_settle_count_rate_for_roi2_30d": "30日订单结算率(%)",
    "total_prepay_and_pay_settle_roi2_90d": "90日结算ROI",
    "total_order_settle_amount_for_roi2_90d": "90日结算金额",
    "total_order_settle_count_for_roi2_90d": "90日结算订单数",
    "total_cost_per_pay_order_settle_for_roi2_90d": "90日结算订单成本(元)",
    "total_order_settle_amount_rate_for_roi2_90d": "90日GMV结算率(%)",
    "total_order_settle_count_rate_for_roi2_90d": "90日订单结算率(%)",
    "live_follow_count_for_roi2": "新增粉丝数",
    "live_comment_count_for_roi2": "直播间评论次数",
    "live_like_count_for_roi2": "直播间点赞次数",
    "additional_delivery_stat_cost_for_roi2_assist": "追投调控消耗(元)",
    "additional_delivery_total_pay_order_count_for_roi2_assist": "追投调控成交订单数",
    "additional_delivery_total_pay_order_gmv_include_coupon_for_roi2_assist": "追投调控成交金额(含优惠券)",
    "additional_delivery_total_prepay_and_pay_order_roi2_assist": "追投调控支付ROI",
    "additional_delivery_show_cnt_for_roi2_assist": "追投调控展示次数",
    "additional_delivery_ctr_for_roi2_assist": "追投调控点击率(%)",
    "additional_delivery_click_cnt_for_roi2_assist": "追投调控点击次数",
    "additional_delivery_convert_rate_for_roi2_assist": "追投调控转化率(%)",
    "additional_delivery_total_pay_order_gmv_for_roi2_assist": "追投调控用户实际支付金额",
    "additional_delivery_total_pay_order_coupon_amount_for_roi2_assist": "追投调控成交智能优惠券金额",
    "additional_delivery_total_ecom_platform_subsidy_amount_for_roi2_assist": "追投调控电商平台补贴金额",
    "additional_delivery_total_unfinished_estimate_order_gmv_for_roi2_assist": "追投调控未完结预售订单预估金额",
    "additional_delivery_pay_convert_cost_for_roi2_assist_v2": "追投调控成交成本(元)",
    "additional_delivery_pay_convert_cnt_for_roi2_assist_v2": "追投调控成交人数",
    "stat_cost_for_overall_roi2": "综合成本(元)"
}

VIDEO_DIM_MAPPING = {
    "stat_time_day": "日期",
    "roi2_material_name_or_id": "全域素材搜索输入",
    "roi2_material_video_name": "全域素材视频名称",
    "roi2_material_video_type": "全域素材视频类型",
    "roi2_material_status": "全域视频素材状态",
    "material_id": "素材ID",
    "roi2_material_advice": "素材建议",
    "anchor_id": "抖音号ID",
    "aggregate_smart_bid_type": "roi2投放类型",
    "ecp_app_id": "下单平台",
    "material_create_time_v2": "创建时间",
    "roi2_material_upload_time": "投放时间",
}

VIDEO_IND_MAPPING = {
    "live_show_count_for_roi2_v2": "整体展现次数",
    "live_watch_count_for_roi2_v2": "整体点击次数",
    "live_cvr_rate_for_roi2_v2": "整体点击率",
    "live_convert_rate_for_roi2_v2": "整体转化率",
    "total_pay_order_count_for_roi2": "整体成交订单数",
    "total_pay_order_gmv_include_coupon_for_roi2": "整体成交金额",
    "total_pay_order_gmv_rate_for_roi2": "整体成交金额占比",
    "stat_cost_for_roi2": "整体消耗",
    "cost_rate_for_roi2": "整体消耗占比",
    "basic_stat_cost_for_roi2_v2": "基础消耗",
    "total_prepay_and_pay_order_roi2": "整体支付ROI",
    "total_cost_per_pay_order_for_roi2": "整体成交订单成本",
    "total_pay_order_gmv_for_roi2": "用户实际支付金额",
    "total_ecpm_for_roi2": "整体千次展现费用",
    "total_cpc_for_roi2": "整体点击单价",
    "total_pay_order_coupon_amount_for_roi2": "整体成交智能优惠券金额",
    "total_ecom_platform_subsidy_amount_for_roi2": "电商平台补贴金额",
    "total_prepay_order_count_for_roi2": "整体预售订单数",
    "total_prepay_order_gmv_for_roi2": "整体预售订单金额",
    "total_unfinished_estimate_order_gmv_for_roi2": "整体未完结预售订单预估金额",
    "stat_cost_for_overall_roi2": "综合成本",
    "total_prepay_and_pay_settle_overall_roi2_1h": "综合净成交ROI",
    "total_cost_per_pay_order_settle_for_overall_roi2_1h": "综合净成交订单成本",
    "total_prepay_and_pay_settle_roi2_1h": "净成交ROI",
    "total_order_settle_amount_for_roi2_1h": "净成交金额",
    "total_order_settle_count_for_roi2_1h": "净成交订单数",
    "total_cost_per_pay_order_settle_for_roi2_1h": "净成交订单成本",
    "total_order_real_settle_amount_for_roi2_1h": "用户实际支付净成交金额",
    "no_refund_ecom_coupon_amount_for_roi2": "智能优惠券未退款金额",
    "no_refund_ecom_platform_subsidy_amount_for_roi2": "电商平台补贴未退款金额",
    "total_order_settle_amount_rate_for_roi2_1h": "净成交金额结算率",
    "total_order_settle_count_rate_for_roi2_1h": "净成交订单结算率",
    "total_refund_order_count_for_roi2_1h": "1小时内退款订单数",
    "total_refund_order_gmv_for_roi2_1h_all": "1小时内退款金额",
    "total_refund_order_gmv_for_roi2_1h_rate": "1小时内退款率",
    "total_prepay_and_pay_settle_roi2_7d": "7日结算ROI",
    "total_order_settle_amount_for_roi2_7d": "7日结算金额",
    "total_order_settle_count_for_roi2_7d": "7日结算订单数",
    "total_cost_per_pay_order_settle_for_roi2_7d": "7日结算订单成本",
    "total_order_settle_amount_rate_for_roi2_7d": "7日GMV结算率",
    "total_order_settle_count_rate_for_roi2_7d": "7日订单结算率",
    "total_prepay_and_pay_settle_roi2_14d": "14日结算ROI",
    "total_order_settle_amount_for_roi2_14d": "14日结算金额",
    "total_order_settle_count_for_roi2_14d": "14日结算订单数",
    "total_cost_per_pay_order_settle_for_roi2_14d": "14日结算订单成本",
    "total_order_settle_amount_rate_for_roi2_14d": "14日GMV结算率",
    "total_order_settle_count_rate_for_roi2_14d": "14日订单结算率",
    "total_prepay_and_pay_settle_roi2_30d": "30日结算ROI",
    "total_order_settle_amount_for_roi2_30d": "30日结算金额",
    "total_order_settle_count_for_roi2_30d": "30日结算订单数",
    "total_cost_per_pay_order_settle_for_roi2_30d": "30日结算订单成本",
    "total_order_settle_amount_rate_for_roi2_30d": "30日GMV结算率",
    "total_order_settle_count_rate_for_roi2_30d": "30日订单结算率",
    "total_prepay_and_pay_settle_roi2_90d": "90日结算ROI",
    "total_order_settle_amount_for_roi2_90d": "90日结算金额",
    "total_order_settle_count_for_roi2_90d": "90日结算订单数",
    "total_cost_per_pay_order_settle_for_roi2_90d": "90日结算订单成本",
    "total_order_settle_amount_rate_for_roi2_90d": "90日GMV结算率",
    "total_order_settle_count_rate_for_roi2_90d": "90日订单结算率",
    "video_like_count_for_roi2": "视频点赞数",
    "video_follow_count_for_roi2": "新增粉丝数",
    "video_avg_watch_duration_for_roi2": "平均观看时长",
    "video_play_count_for_roi2_v2": "视频播放数",
    "video_play_finish_count_for_roi2_v2": "视频完播数",
    "video_play_finish_rate_for_roi2_v2": "视频完播率",
    "video_comment_count_for_roi2_v2": "视频评论数",
    "video_play_duration_2s_rate_for_roi2": "2秒播放率",
    "video_play_duration_3s_rate_for_roi2": "3秒播放率",
    "video_play_duration_5s_rate_for_roi2": "5秒播放率",
    "video_play_duration_10s_rate_for_roi2": "10秒播放率",
    "heat_stat_cost_for_roi2": "追投消耗",
    "heat_total_pay_order_count_for_roi2": "追投成交订单数",
    "heat_total_pay_order_gmv_for_roi2": "追投成交金额",
    "heat_total_prepay_and_pay_order_roi2": "追投ROI",
    "additional_delivery_stat_cost_for_roi2_assist": "追投调控消耗",
    "additional_delivery_total_pay_order_count_for_roi2_assist": "追投调控成交订单数",
    "additional_delivery_total_pay_order_gmv_include_coupon_for_roi2_assist": "追投调控成交金额",
    "additional_delivery_total_prepay_and_pay_order_roi2_assist": "追投调控支付ROI",
    "additional_delivery_show_cnt_for_roi2_assist": "追投调控展示次数",
    "additional_delivery_ctr_for_roi2_assist": "追投调控点击率",
    "additional_delivery_click_cnt_for_roi2_assist": "追投调控点击次数",
    "additional_delivery_convert_rate_for_roi2_assist": "追投调控转化率",
    "additional_delivery_total_pay_order_gmv_for_roi2_assist": "追投调控用户实际支付金额",
    "additional_delivery_total_pay_order_coupon_amount_for_roi2_assist": "追投调控成交智能优惠券金额",
    "additional_delivery_total_ecom_platform_subsidy_amount_for_roi2_assist": "追投调控电商平台补贴金额",
    "additional_delivery_total_unfinished_estimate_order_gmv_for_roi2_assist": "追投调控未完结预售订单预估金额",
    "additional_delivery_pay_convert_cost_for_roi2_assist_v2": "追投调控成交成本",
    "additional_delivery_pay_convert_cnt_for_roi2_assist_v2": "追投调控成交人数"
}

OTHER_MAPPING = {
    "total_pay_order_count_for_roi2": "整体成交订单数",
    "total_pay_order_gmv_include_coupon_for_roi2": "整体成交金额",
    "total_pay_order_gmv_rate_for_roi2": "整体成交金额占比",
    "total_pay_order_gmv_for_roi2": "用户实际支付金额",
    "total_pay_order_coupon_amount_for_roi2": "整体成交智能优惠券金额",
    "total_ecom_platform_subsidy_amount_for_roi2": "电商平台补贴金额",
    "total_prepay_order_count_for_roi2": "整体预售订单数",
    "total_prepay_order_gmv_for_roi2": "整体预售订单金额",
    "total_unfinished_estimate_order_gmv_for_roi2": "整体未完结预售订单预估金额"
}

DIM_VALUE_MAPPING = {
    "roi2_material_video_type": {"3": "智能优选视频", "1": "全部", "2": "自选投放视频"},
    "roi2_material_status": {"2": "已删除", "1": "投放中"},
    "roi2_material_advice": {"8": "优质素材", "10": "低质素材", "4": "搬运素材", "5": "低效素材", "6": "首发素材"},
    "aggregate_smart_bid_type": {"7": "放量投放", "0": "控成本投放"},
    "ecp_app_id": {"1": "千川pc", "2": "小店随心推"}
}

API_CONFIG = {
    "base_url": "https://api.oceanengine.com/open_api",
    "timeout": 30
}

MODULE_CONFIG = {
    "live": {
        "max_workers": 40,
        "max_retries": 10,
        "base_delay": 1,
        "page_size": 100,
        "data_topic": "SITE_PROMOTION_POST_DATA_LIVE",
        "table_name": "ods_千川素材_直播画面_m"
    },
    "video": {
        "max_workers": 40,
        "max_retries": 10,
        "base_delay": 1,
        "page_size": 100,
        "data_topic": "SITE_PROMOTION_POST_DATA_VIDEO",
        "table_name": "ods_千川素材_视频_M"
    },
    "other": {
        "max_workers": 40,
        "max_retries": 10,
        "base_delay": 1,
        "page_size": 100,
        "data_topic": "SITE_PROMOTION_POST_DATA_OTHER",
        "table_name": "ods_千川素材_其他"
    }
}

DEFAULT_TABLE_NAMES = {
    "live": "ods_千川素材_直播画面_m",
    "video": "ods_千川素材_视频_M",
    "other": "ods_千川素材_其他"
}
